server:
  port: 10080
# druid Á¬½Ó³ØÅäÖÃ
spring:
  application:
    name: admin-user
  boot:
    admin:
      client:
        # Spring Boot Admin æœåŠ¡ç«¯åœ°å€
        url: "http://localhost:10086/"
        instance:
          metadata:
            # å®¢æˆ·ç«¯ç«¯ç‚¹ä¿¡æ¯çš„å®‰å…¨è®¤è¯ä¿¡æ¯
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}
  security:
    user:
      name: admin
      password: 123456
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://192.168.4.188:3306/xxadmin?serverTimezone=GMT%2B8
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # ÅäÖÃ»ñÈ¡Á¬½ÓµÈ´ı³¬Ê±µÄÊ±¼ä
    maxWait: 60000
    # ÅäÖÃ¼ä¸ô¶à¾Ã²Å½øĞĞÒ»´Î¼ì²â£¬¼ì²âĞèÒª¹Ø±ÕµÄ¿ÕÏĞÁ¬½Ó£¬µ¥Î»ÊÇºÁÃë
    timeBetweenEvictionRunsMillis: 60000
    # ÅäÖÃÒ»¸öÁ¬½ÓÔÚ³ØÖĞ×îĞ¡Éú´æµÄÊ±¼ä£¬µ¥Î»ÊÇºÁÃë
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # ÅäÖÃ¼à¿ØÍ³¼ÆÀ¹½ØµÄfilters£¬È¥µôºó¼à¿Ø½çÃæsqlÎŞ·¨Í³¼Æ£¬'wall'ÓÃÓÚ·À»ğÇ½
    filters: stat,wall,log4j
    logSlowSql: true
  jpa:
    show-sql: true
    open-in-view: false
  redis:
    host: 192.168.4.188
  profiles:
    active: dev

# adminé…ç½®
management:
  endpoint:
    health:
      # ç«¯ç‚¹å¥åº·æƒ…å†µï¼Œé»˜è®¤å€¼"never"ï¼Œè®¾ç½®ä¸º"always"å¯ä»¥æ˜¾ç¤ºç¡¬ç›˜ä½¿ç”¨æƒ…å†µå’Œçº¿ç¨‹æƒ…å†µ
      show-details: always
  endpoints:
    web:
      exposure:
        # è®¾ç½®ç«¯ç‚¹æš´éœ²çš„å“ªäº›å†…å®¹ï¼Œé»˜è®¤["health","info"]ï¼Œè®¾ç½®"*"ä»£è¡¨æš´éœ²æ‰€æœ‰å¯è®¿é—®çš„ç«¯ç‚¹
        include: "*"